

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="generator" content="HTML Tidy for HTML5 (experimental) for Mac OS X https://github.com/w3c/tidy-html5/tree/c63cc39"/>

    <title></title>
  </head>

  <body>
    <section xmlns="http://www.w3.org/1999/xhtml" id="error-handling" data-type="chapter">
      <h1>Error Handling</h1>

      <p>
	Nobody likes dealing with errors. It's tedious, it's easy to
	get wrong, and it's usually just not as fun as thinking about
	how your program is going to succeed. But error handling is
	important, and however much you don't like thinking about it,
	having your software fail due to poor error handling is
	worse.</p>

      <p>
	Thankfully, OCaml has powerful tools for handling errors
	reliably and with a minimum of pain. In this chapter we'll
	discuss some of the different approaches in OCaml to handling
	errors, and give some advice on how to design interfaces that
	make error handling easier.</p>

      <p>
	We'll start by describing the two basic approaches for
	reporting errors in OCaml: error-aware return types and
	exceptions.

	<idx id="erraware">error-aware return types</idx>
	<idx id="EHeraware">error handling/error-aware return types</idx></p>

      <section id="error-aware-return-types" data-type="sect1">
	<h1>Error-Aware Return Types</h1>

	<p>
	  The best way in OCaml to signal an error is to include that
	  error in your return value. Consider the type of
	  the <code>find</code> function in the <code>List</code>
	  module:</p>

	<link rel="import" href="code/error-handling/main.mlt" part="0.5"/>

	<p>
	  The option in the return type indicates that the function
	  may not succeed in finding a suitable element:</p>

	<link rel="import" href="code/error-handling/main.mlt" part="1"/>

	<p>
	  Including errors in the return values of your functions
	  requires the caller to handle the error explicitly, allowing
	  the caller to make the choice of whether to recover from the
	  error or propagate it onward.</p>

	<p>
	  Consider the <code>compute_bounds</code> function below,
	  which takes a list and a comparison function and returns
	  upper and lower bounds for the list by finding the smallest
	  and largest element on the list. <code>List.hd</code> and
	  <code>List.last</code>, which return <code>None</code> when
	  they encounter an empty list, are used to extract the largest
	  and smallest element of the list:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="2"/>

	<p>
	  The <code>match</code> statement is used to handle the
	  error cases, propagating a <code>None</code> in
	  <code>hd</code> or <code>last</code> into the return value of
	  <code>compute_bounds</code>.</p>

	<p>
	  On the other hand, in the <code>find_mismatches</code>
	  that follows, errors encountered during the computation do
	  not propagate to the return value of the function.
	  <code>find_mismatches</code> takes two hash tables as
	  arguments and searches for keys that have different data in
	  one table than in the other. As such, the failure to find a
	  key in one table isn't a failure of any sort:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="3"/>

	<p>
	  The use of options to encode errors underlines the fact
	  that it's not clear whether a particular outcome, like not
	  finding something on a list, is an error or is just another
	  valid outcome. This depends on the larger context of your
	  program, and thus is not something that a general-purpose
	  library can know in advance. One of the advantages of
	  error-aware return types is that they work well in both
	  situations.</p>

	<section id="encoding-errors-with-result" data-type="sect2">
          <h2>Encoding Errors with Result</h2>

          <p>
	    Options aren't always a sufficiently expressive way to
            report errors. Specifically, when you encode an error as
            <code>None</code>, there's nowhere to say anything about
            the nature of the error.</p>

          <p>
	    <code>Result.t</code> is meant to address this
            deficiency. The type is defined as follows:<idx>Result.t
              option</idx></p>
          <link rel="import" href="code/error-handling/result.mli"/>

          <p>
	    A <code>Result.t</code> is essentially an option augmented
            with the ability to store other information in the error
            case. Like <code>Some</code> and <code>None</code> for
            options, the constructors <code>Ok</code>
            and <code>Error</code> are available at the toplevel. As
            such, we can write:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="4"/>

          <p>
	    without first opening the <code>Result</code>
            module.</p>
	</section>

	<section id="error-and-or_error" data-type="sect2">
          <h2>Error and Or_error</h2>

          <p>
	    <code>Result.t</code> gives you complete freedom to
            choose the type of value you use to represent errors, but
            it's often useful to standardize on an error type. Among
            other things, this makes it easier to write utility
            functions to automate common error handling
            patterns.<idx>Error.t type</idx></p>

          <p>
	    But which type to choose? Is it better to represent
            errors as strings? Some more structured representation like
            XML? Or something else entirely?</p>

          <p>
	    Base's answer to this question is the
            <code>Error.t</code> type, which tries to forge a good
            compromise between efficiency, convenience, and control
            over the presentation of errors.</p>

          <p>
	    It might not be obvious at first why efficiency is an
            issue at all. But generating error messages is an expensive
            business. An ASCII representation of a value can be quite
            time-consuming to construct, particularly if it includes
            expensive-to-convert numerical data.</p>

          <p>
	    <code>Error</code> gets around this issue through
            laziness. In particular, an <code>Error.t</code> allows you
            to put off generation of the error string until and unless
            you need it, which means a lot of the time you never have
            to construct it at all. You can of course construct an
            error directly from a string:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="5"/>

          <p>
	    But you can also construct an <code>Error.t</code> from
            a <em>thunk</em>, i.e., a function that takes a single
            argument of type <code>unit</code>:<idx>thunks</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="6"/>

          <p>
	    In this case, we can benefit from the laziness of
            <code>Error</code>, since the thunk won't be called unless
            the <code>Error.t</code> is converted to a string.</p>

          <p>
	    The most common way to create <code>Error.t</code>s is
            using <em>s-expressions</em>. An s-expression is a balanced
            parenthetical expression where the leaves of the
            expressions are strings. Here's a simple example:
            <idx>s-expressions/example of</idx></p>
          <link rel="import" href="code/error-handling/sexpr.scm"/>

          <p>
	    S-expressions are supported by the Sexplib package that
            is distributed with Base and is the most common
            serialization format used in Base. Indeed, most types in
            Base come with built-in s-expression converters.


            <idx>Sexplib package/sexp converter</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="7"/>

          <p>
	    Note that the character isn't actually serialized into an
            s-expression until the error is printed out.</p>

          <p>
	    We're not restricted to doing this kind of error
            reporting with built-in types. This will be discussed in
            more detail in <a href="17-data-serialization.html#data-serialization-with-s-expressions" data-type="xref">Data Serialization With S Expressions</a>,
            but Sexplib comes with a language extension that can
            autogenerate sexp converters for newly generated types:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="8"/>

          <p>
	    We can use this same idiom for generating an error:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="9"/>

          <p>
	    <code>Error</code> also supports operations for
            transforming errors. For example, it's often useful to
            augment an error with information about the context of the
            error or to combine multiple errors together.
            <code>Error.tag</code> and <code>Error.of_list</code>
            fulfill these
            roles:<idx>Error.of_list</idx><idx>Error.tag</idx><idx>errors/transformation
              of</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="10"/>

          <p>
	    The type <code>'a Or_error.t</code> is just a shorthand
            for <code>('a,Error.t) Result.t</code>, and it is, after
            <code>option</code>, the most common way of returning
            errors in Base.</p>
	</section>

	<section id="bind-and-other-error-handling-idioms" data-type="sect2">
          <h2><code>bind</code> and Other Error Handling Idioms</h2>

          <p>
	    As you write more error handling code in OCaml, you'll
            discover that certain patterns start to emerge. A number of
            these common patterns have been codified by functions in
            modules like <code>Option</code> and <code>Result</code>.
            One particularly useful pattern is built around the
            function <code>bind</code>, which is both an ordinary
            function and an infix operator <code>&gt;&gt;=</code>.
            Here's the definition of <code>bind</code> for options:
            <idx>bind function</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="11"/>

          <p>
	    As you can see, <code>bind None f</code> returns
            <code>None</code> without calling <code>f</code>, and
            <code>bind (Some x) f</code> returns <code>f x</code>.
            <code>bind</code> can be used as a way of sequencing
            together error-producing functions so that the first one to
            produce an error terminates the computation. Here's a
            rewrite of <code>compute_bounds</code> to use a nested
            series of <code>bind</code>s:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="12"/>

          <p>
	    The preceding code is a little bit hard to swallow,
            however, on a syntactic level. We can make it easier to
            read and drop some of the parentheses, by using the infix
            operator form of <code>bind</code>, which we get access to
            by locally opening <code>Option.Monad_infix</code>. The
            module is called <code>Monad_infix</code> because the
            <code>bind</code> operator is part of a subinterface called
            <code>Monad</code>, which we'll see again in <a href="18-concurrent-programming.html#concurrent-programming-with-async" data-type="xref">Concurrent Programming With Async</a>.</p>
          <link rel="import" href="code/error-handling/main.mlt" part="13"/>

          <p>
	    This use of <code>bind</code> isn't really materially
            better than the one we started with, and indeed, for small
            examples like this, direct matching of options is generally
            better than using <code>bind</code>. But for large, complex
            examples with many stages of error handling, the
            <code>bind</code> idiom becomes clearer and easier to
            manage.</p>

	  <div data-type="note">
	    <h1>Monads and <code>Let_syntax</code></h1>
	    <p>
	      We can make this look a little bit more ordinary by
	      using a syntax extension that's designed specifically
	      for monadic binds, called <code>Let_syntax</code>.
	      Here's what the above example looks like using this
	      extension. </p>
	    <link rel="import" href="code/error-handling/main.mlt" part="13.1"/>

	    <p>To understand what's going on here, you need to know
	    that <code>let%bind x = some_expr in
	    some_other_expr</code> is rewritten into <code>some_expr
	    >>= fun x -> some_other_expr</code>.
	    </p>

	    <p>The advantage of <code>Let_syntax</code> is that it
	      makes monadic bind look more like a regular let-binding.
	      This works nicely because you can think of the monadic
	      bind in this case as a special form of let binding that
	      has some built-in error handling semantics.
	    <p>
	  </div>

          <p>
	    There are other useful idioms encoded in the functions
            in <code>Option</code>. One example is
            <code>Option.both</code>, which takes two optional values
            and produces a new optional pair that is <code>None</code>
            if either of its arguments are <code>None</code>. Using
            <code>Option.both</code>, we can make
            <code>compute_bounds</code> even shorter:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="14"/>

          <p>
	    These error-handling functions are valuable because they
            let you express your error handling both explicitly and
            concisely. We've only discussed these functions in the
            context of the <code>Option</code> module, but more
            functionality of this kind can be found in the
            <code>Result</code> and <code>Or_error</code>
            modules.<a data-type="indexterm" data-startref="erraware">&nbsp;</a><a data-type="indexterm" data-startref="EHeraware">&nbsp;</a></p>
	</section>
      </section>

      <section id="exceptions" data-type="sect1">
	<h1>Exceptions</h1>

	<p>
	  Exceptions in OCaml are not that different from exceptions
	  in many other languages, like Java, C#, and Python.
	  Exceptions are a way to terminate a computation and report an
	  error, while providing a mechanism to catch and handle (and
	  possibly recover from) exceptions that are triggered by
	  subcomputations.<idx>exceptions/usefulness of</idx><idx>error
	    handling/exceptions</idx></p>

	<p>
	  You can trigger an exception by, for example, dividing an
	  integer by zero:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="15"/>

	<p>
	  And an exception can terminate a computation even if it
	  happens nested somewhere deep within it:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="16"/>

	<p>
	  If we put a <code>printf</code> in the middle of the
	  computation, we can see that <code>List.map</code> is
	  interrupted partway through its execution, never getting to
	  the end of the list:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="17"/>

	<p>
	  In addition to built-in exceptions like
	  <code>Divide_by_zero</code>, OCaml lets you define your
	  own:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="18"/>

	<p>
	  Exceptions are ordinary values and can be manipulated just
	  like other OCaml values:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="19"/>

	<p>
	  Exceptions are all of the same type, <code>exn</code>. The
	  <code>exn</code> type is something of a special case in the
	  OCaml type system. It is similar to the variant types we
	  encountered in <a href="06-variants.html#variants" data-type="xref">Variants</a>, except that it is <em>open</em>, meaning
	  that it's not fully defined in any one place. In particular,
	  new tags (specifically, new exceptions) can be added to it by
	  different parts of the program. This is in contrast to
	  ordinary variants, which are defined with a closed universe
	  of available tags. One result of this is that you can never
	  have an exhaustive match on an <code>exn</code>, since the
	  full set of possible exceptions is not known.<idx>exn
	    type</idx></p>

	<p>
	  The following function uses the <code>Key_not_found</code>
	  exception we defined above to signal an error:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="20"/>

	<p>
	  Note that we named the function <code>find_exn</code> to
	  warn the user that the function routinely throws exceptions,
	  a convention that is used heavily in
	  Base.<idx>functions/exception warnings for</idx><idx>find_exn
	    function</idx></p>

	<p>
	  In the preceding example, <code>raise</code> throws the
	  exception, thus terminating the computation. The type of
	  raise is a bit surprising when you first see it:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="21"/>

	<p>
	  The return type of <code>'a</code> makes it look like
	  <code>raise</code> manufactures a value to return that is
	  completely unconstrained in its type. That seems impossible,
	  and it is. Really, <code>raise</code> has a return type of
	  <code>'a</code> because it never returns at all. This
	  behavior isn't restricted to functions like
	  <code>raise</code> that terminate by throwing exceptions.
	  Here's another example of a function that doesn't return a
	  value:</p>
	<link rel="import" href="code/error-handling/main.mlt" part="22"/>

	<p>
	  <code>forever</code> doesn't return a value for a
	  different reason: it's an infinite loop.</p>

	<p>
	  This all matters because it means that the return type of
	  <code>raise</code> can be whatever it needs to be to fit into
	  the context it is called in. Thus, the type system will let
	  us throw an exception anywhere in a program. <idx>sexp
	    declaration</idx> <idx>exceptions/textual representation
	    of</idx></p>

	<div class="allow_break" data-type="note">
          <h1>Declaring Exceptions Using <code>[@@deriving sexp]</code></h1>

          <p>
	    OCaml can't always generate a useful textual representation
            of an exception. For example:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="23"/>

          <p>
	    But if we declare the exception (and the types it depends
	    on) using <code>[@@deriving sexp]</code>, we'll get something with
	    more information:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="24"/>

          <p>
	    The period in front of <code>Crossed_bounds</code> is there
            because the representation generated by <code>[@@deriving
              sexp]</code> includes the full module path of the module
            where the exception in question is defined. In this case,
            the string <code>//toplevel//</code> is used to indicate
            that this was declared at the utop prompt, rather than in
            a module.</p>

          <p>
	    This is all part of the support for s-expressions provided
            by the Sexplib library and syntax extension, which is
            described in more detail
            in <a href="17-data-serialization.html#data-serialization-with-s-expressions"
            data-type="xref">Data Serialization With
            S-Expressions</a>.</p>
	</div>

	<section id="helper-functions-for-throwing-exceptions" data-type="sect2">
          <h2>Helper Functions for Throwing Exceptions</h2>

          <p>
	    Base provides a number of helper functions to simplify the
            task of throwing exceptions. The simplest one
            is <code>failwith</code>, which could be defined as
            follows:

	    <idx>exceptions/helper functions for</idx>
	    <idx>error handling/exception helper functions</idx></p>

          <link rel="import" href="code/error-handling/main.mlt" part="25"/>

          <p>
	    There are several other useful functions for raising
            exceptions, which can be found in the API documentation for
            the <code>Common</code> and <code>Exn</code> modules in
            Base.</p>

          <p>
	    Another important way of throwing an exception is the
            <code>assert</code> directive. <code>assert</code> is used
            for situations where a violation of the condition in
            question indicates a bug. Consider the following piece of
            code for zipping together two lists:<idx>assert
              directive</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="26"/>

          <p>
	    Here we use <code>assert false</code>, which means that
            the <code>assert</code> is guaranteed to trigger. In
            general, one can put an arbitrary condition in the
            assertion.</p>

          <p>
	    In this case, the <code>assert</code> can never be
            triggered because we have a check that makes sure that the
            lists are of the same length before we call
            <code>loop</code>. If we change the code so that we drop
            this test, then we can trigger the <code>assert</code>:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="27"/>

          <p>
	    This shows what's special about <code>assert</code>: it
            captures the line number and character offset of the source
            location from which the assertion was made.</p>
	</section>

	<section id="exception-handlers" data-type="sect2">
          <h2>Exception Handlers</h2>

          <p>
	    So far, we've only seen exceptions fully terminate the
            execution of a computation. But often, we want a program to
            be able to respond to and recover from an exception. This
            is achieved through the use of <em>exception
              handlers</em>.<idx>exceptions/exception
              handlers</idx><idx>error handling/exception
              handlers</idx></p>

          <p>
	    In OCaml, an exception handler is declared using a
            <code>try</code>/<code>with</code> statement. Here's the
            basic syntax.</p>
          <link rel="import" href="code/error-handling/try_with.syntax"/>

          <p>
	    A <code>try/with</code> clause first evaluates its body,
            <em><code>expr</code></em>. If no exception is thrown, then
            the result of evaluating the body is what the entire
            <code>try/with</code> clause evaluates to.</p>

          <p>
	    But if the evaluation of the body throws an exception,
            then the exception will be fed to the pattern-match
            statements following the <code>with</code>. If the
            exception matches a pattern, then we consider the exception
            caught, and the <code>try/with</code> clause evaluates to
            the expression on the righthand side of the matching
            pattern.</p>

          <p>
	    Otherwise, the original exception continues up the stack
            of function calls, to be handled by the next outer
            exception handler. If the exception is never caught, it
            terminates the program.</p>
	</section>

	<section id="cleaning-up-in-the-presence-of-exceptions" data-type="sect2">
          <h2>Cleaning Up in the Presence of Exceptions</h2>

          <p>
	    One headache with exceptions is that they can terminate
            your execution at unexpected places, leaving your program
            in an awkward state. Consider the following function for
            loading a file full of numerical data.  This code parses
            data that matches a simple comma-separated file format,
            where each field is a floating point number. In this
            example we open <code>Stdio</code>, to get access to
            routines for reading from files.

	    <idx>exceptions/exception clean up</idx>
	    <idx>error handling/exception clean up</idx></p>

          <link rel="import" href="code/error-handling/main.mlt" 
		part="28"/>

          <p>
	    One problem with this code is that the parsing function
	    can throw an exception if the file in question is
	    malformed.  Unfortunately, that means that
            the <code>In_channel.t</code> that was opened will never
            be closed, leading to a file-descriptor leak.</p>

          <p>
	    We can fix this using Base's <code>Exn.protect</code>
            function, which takes two arguments: a
            thunk <code>f</code>, which is the main body of the
            computation to be run; and a thunk <code>finally</code>,
            which is to be called when <code>f</code> exits, whether
            it exits normally or with an exception. This is similar to
            the <code>try/finally</code> construct available in many
            programming languages, but it is implemented in a library,
            rather than being a built-in primitive. Here's how it
            could be used to fix our <code>load</code> function:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="29"/>

          <p>
	    This is a common enough problem
            that <code>In_channel</code> has a function
            called <code>with_file</code> that automates this
            pattern:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="30"/>

          <p>
	    <code>In_channel.with_file</code> is built on top
            of <code>protect</code> so that it can clean up after
            itself in the presence of exceptions.</p>
	</section>

	<section id="catching-specific-exceptions" data-type="sect2">
          <h2>Catching Specific Exceptions</h2>

          <p>
	    OCaml's exception-handling system allows you to tune
            your error-recovery logic to the particular error that was
            thrown. For example, <code>List.find_exn</code> throws
            <code>Not_found</code> when the element in question can't
            be found. Let's look at an example of how you could take
            advantage of this. In particular, consider the following
            function:

	    <idx>exceptions/catching specific</idx>
	    <idx>error handling/exception detection</idx></p>

          <link rel="import" href="code/error-handling/main.mlt" part="31"/>

          <p>
	    As you can see from the type, <code>lookup_weight</code>
            takes an association list, a key for looking up a
            corresponding value in that list, and a function for
            computing a floating-point weight from the looked-up value.
            If no value is found, then a weight of <code>0.</code>
            should be returned.</p>

          <p>
	    The use of exceptions in this code, however, presents
            some problems. In particular, what happens if
            <code>compute_weight</code> throws an exception? Ideally,
            <code>lookup_weight</code> should propagate that exception
            on, but if the exception happens to be
            <code>Not_found</code>, then that's not what will
            happen:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="32"/>

          <p>
	    This kind of problem is hard to detect in advance because
            the type system doesn't tell you what exceptions a given
            function might throw. For this reason, it's generally better
            to avoid relying on the identity of the exception to determine
            the nature of a failure. A better approach is to narrow the
            scope of the exception handler, so that when it fires it's
            very clear what part of the code failed:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="33"/>

	  <p>

	    This nesting of a <code>try</code> within
	    a <code>match</code> statement is both awkward and involves
	    some unnecessary computation (in particular, the allocation of
	    the option).  Happily, OCaml allows for exceptions to be
	    caught by match statements directly, which lets you write
	    this more concisely as follows.</p>

          <link rel="import" href="code/error-handling/main.mlt" part="33.1"/>

	  <p>

	    Note that the <code>exception</code> keyword is used to mark
	    the exception-handling cases.</p>

          <p>

	    Best of all is to avoid exceptions entirely, which we could
	    do by using the exception-free
            function, <code>List.Assoc.find</code>, instead:</p>

          <link rel="import" href="code/error-handling/main.mlt" part="34"/>
	</section>

	<section id="backtraces" data-type="sect2">
          <h2>Backtraces</h2>

          <p>
	    A big part of the value of exceptions is that they
            provide useful debugging information in the form of a stack
            backtrace. Consider the following simple
            program:<idx>debugging/stack backtraces</idx><idx>stack
              backtraces</idx><idx>backtraces</idx>:<idx>exceptions/stack
              backtraces for</idx><idx>error handling/exception
              backtracing</idx></p>
          <link rel="import" href="code/error-handling/blow_up/blow_up.ml"/>

          <p>
	    If we build and run this program, we'll get a stack
            backtrace that will provide some information about where
            the error occurred and the stack of function calls that
            were in place at the time of the error:</p>
          <link rel="import" href="code/error-handling/blow_up/jbuild"/>
          <link rel="import" href="code/error-handling/blow_up/build_blow_up.errsh" part="trace"/>

          <p>
	    You can also capture a backtrace within your program by
            calling <code>Exn.backtrace</code>, which returns the
            backtrace of the most recently thrown exception. This is
            useful for reporting detailed information on errors that
            did not cause your program to fail.<idx>Exn
              module/Exn.backtrace</idx></p>

          <p>
	    This works well if you have backtraces enabled, but that
            isn't always the case. In fact, by default, OCaml has
            backtraces turned off, and even if you have them turned on
            at runtime, you can't get backtraces unless you have
            compiled with debugging symbols. Core reverses the default,
            so if you're linking in Core, you will have backtraces
            enabled by default.</p>

          <p>
	    Even using Core and compiling with debugging symbols,
            you can turn backtraces off by setting the
            <code>OCAMLRUNPARAM</code> environment variable to be
            empty:</p>
          <link rel="import" href="code/error-handling/blow_up/jbuild"/>
          <link rel="import" href="code/error-handling/blow_up/build_blow_up.errsh" part="no_trace"/>

          <p>
	    The resulting error message is considerably less
            informative. You can also turn backtraces off in your code
            by calling <code>Backtrace.Exn.set_recording
              false</code>.<idx>Exn module/Backtrace.Exn.set_recording
              false</idx></p>

          <p>
	    There is a legitimate reasons to run without backtraces:
            speed. OCaml's exceptions are fairly fast, but they're even
            faster still if you disable backtraces. Here's a simple
            benchmark that shows the effect, using the
            <code>core_bench</code> package:</p>
          <link rel="import" href="code/error-handling/exn_cost/exn_cost.ml"/>

          <p>
	    We're testing three cases here: a simple computation
            with no exceptions; the same computation with an exception
            handler but no thrown exceptions; and finally the same
            computation where we use the exception to do the control
            flow back to the caller.</p>

          <p>
	    If we run this with stacktraces on, the benchmark
            results look like this:</p>
          <link rel="import" href="code/error-handling/exn_cost/jbuild"/>
          <link rel="import" href="code/error-handling/exn_cost/run_exn_cost.sh"/>

          <p>
	    Here, we see that we lose something like 30 cycles to
            adding an exception handler, and 60 more to actually
            throwing and catching an exception. If we turn backtraces
            off, then the results look like this:</p>
          <link rel="import" href="code/error-handling/exn_cost/run_exn_cost_notrace.sh"/>

          <p>
	    Here, the handler costs about the same, but the
            exception itself costs only 25, as opposed to 60 additional
            cycles. All told, this should only matter if you're using
            exceptions routinely as part of your flow control, which is
            in most cases a stylistic mistake anyway.</p>
	</section>

	<section id="from-exceptions-to-error-aware-types-and-back-again" data-type="sect2">
          <h2>From Exceptions to Error-Aware Types and Back
            Again</h2>

          <p>
	    Both exceptions and error-aware types are necessary
            parts of programming in OCaml. As such, you often need to
            move between these two worlds. Happily, Core comes with
            some useful helper functions to help you do just that. For
            example, given a piece of code that can throw an exception,
            you can capture that exception into an option as
            follows:<idx>exceptions/and error-aware
              types</idx><idx>error-aware return types</idx><idx>error
              handling/combining exceptions and error-aware
              types</idx></p>
          <link rel="import" href="code/error-handling/main.mlt" part="35"/>

          <p>
	    And <code>Result</code> and <code>Or_error</code> have
            similar <code>try_with</code> functions. So, we could
            write:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="36"/>

          <p>
	    And then we can reraise that exception:</p>
          <link rel="import" href="code/error-handling/main.mlt" part="37"/>
	</section>
      </section>

      <section id="choosing-an-error-handling-strategy" data-type="sect1">
	<h1>Choosing an Error-Handling Strategy</h1>

	<p>
	  Given that OCaml supports both exceptions and error-aware
	  return types, how do you choose between them? The key is to
	  think about the trade-off between concision and
	  explicitness.<idx data-seealso="errors">error
	    handling/strategy choice</idx></p>

	<p>
	  Exceptions are more concise because they allow you to
	  defer the job of error handling to some larger scope, and
	  because they don't clutter up your types. But this concision
	  comes at a cost: exceptions are all too easy to ignore.
	  Error-aware return types, on the other hand, are fully
	  manifest in your type definitions, making the errors that
	  your code might generate explicit and impossible to
	  ignore.<idx>exceptions/benefits and drawbacks of</idx></p>

	<p>
	  The right trade-off depends on your application. If you're
	  writing a rough-and-ready program where getting it done
	  quickly is key and failure is not that expensive, then using
	  exceptions extensively may be the way to go. If, on the other
	  hand, you're writing production software whose failure is
	  costly, then you should probably lean in the direction of
	  using error-aware return types.</p>

	<p>
	  To be clear, it doesn't make sense to avoid exceptions
	  entirely. The maxim of "use exceptions for exceptional
	  conditions" applies. If an error occurs sufficiently rarely,
	  then throwing an exception is often the right behavior.</p>

	<p>
	  Also, for errors that are omnipresent, error-aware return
	  types may be overkill. A good example is out-of-memory
	  errors, which can occur anywhere, and so you'd need to use
	  error-aware return types everywhere to capture those. Having
	  every operation marked as one that might fail is no more
	  explicit than having none of them marked.</p>

	<p>
	  In short, for errors that are a foreseeable and ordinary
	  part of the execution of your production code and that are
	  not omnipresent, error-aware return types are typically the
	  right solution.</p>
      </section>
    </section>
  </body>
</html>
